[default]
server_port = 5000
server_host = "ec2-35-177-62-21.eu-west-2.compute.amazonaws.com"
log_level = "debug"
worker_threads = 4
env = "development"
db_host = "127.0.0.1"
db_port = 27017
db_name = "interactions_db"
